### ISSUE TITLE
NameError: uninitialized constant RedmineIssueFieldVisibility::VersionPatch::VersionFixedIssuesAssociationExtension

### ISSUE THREAD

**Issue by ebartlomiej89** [planio-gmbh/redmine_issue_field_visibility#10]
Redmine Version: **4.0.4**

After command:

`bundle exec rake redmine:plugins:migrate RAILS_ENV=production --trace`

an error occurred

```
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant RedmineIssueFieldVisibility::VersionPatch::VersionFixedIssuesAssociationExtension
/var/www/redmine/plugins/redmine_issue_field_visibility/lib/redmine_issue_field_visibility/version_patch.rb:15:in `apply'
/var/www/redmine/plugins/redmine_issue_field_visibility/lib/redmine_issue_field_visibility.rb:13:in `setup'
/var/www/redmine/plugins/redmine_issue_field_visibility/init.rb:22:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:605:in `catch'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `each'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `invoke_before'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.3.4/gems/activesupport-5.2.3/lib/active_support/reloader.rb:89:in `prepare!'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-5.2.3/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/var/www/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.3.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/usr/local/rvm/gems/ruby-2.3.4/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.4/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.3.4/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

**Comment by tofi86** [comment]
I also encountered this issue today with Redmine 3.4.13

The latest two commits also show this error in the Travis CI build.

@jkraemer is there any chance to get this fixed?

Thanks,
Tobias
