### ISSUE TITLE
Not compatible with 4.1

### ISSUE THREAD

**Issue by lublasco** [planio-gmbh/redmine_issue_field_visibility#13]
Hi,

when trying to install in Redmine 4.1 bundle exec rake command shows the following error:

```
rake aborted!
NameError: uninitialized constant RedmineIssueFieldVisibility::VersionPatch::VersionFixedIssuesAssociationExtension
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_issue_field_visibility/lib/redmine_issue_field_visibility/version_patch.rb:15:in `apply'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_issue_field_visibility/lib/redmine_issue_field_visibility.rb:13:in `setup'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_issue_field_visibility/init.rb:22:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:16:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

Could you please check if there is an easy solution for this issue?
Is there any chance you could make your nice plugin compatible with the new Redmine version?

Thanks in advance!

**Comment by jkraemer** [comment]
this specific problem wasn't related to the redmine version (see #10)
