### ISSUE TITLE
Cannot be installed on Redmine 3.2.1 => undefined method `apply' for QueriesHelperPatch:Module

### ISSUE THREAD

**Issue by abatista75** [planio-gmbh/redmine_issue_field_visibility#5]
Hereafter are the logs:

```
(in /usr/share/redmine-3.2.1)
rake aborted!
undefined method `apply' for QueriesHelperPatch:Module
/usr/share/redmine-3.2.1/plugins/redmine_issue_field_visibility/lib/redmine_issue_field_visibility.rb:8:in `setup'
/usr/share/redmine-3.2.1/plugins/redmine_issue_field_visibility/init.rb:22:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:192:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.5.2/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.5.2/lib/rails/application.rb:352:in `initialize!'
/usr/share/redmine-3.2.1/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/usr/share/redmine-3.2.1/plugins/a_common_libs/lib/tasks/saas.rake:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/usr/share/redmine-3.2.1/lib/tasks/redmine.rake:186:in `block in <top (required)>'
/usr/share/redmine-3.2.1/lib/tasks/redmine.rake:186:in `each'
/usr/share/redmine-3.2.1/lib/tasks/redmine.rake:186:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.5.2/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.5.2/lib/rails/engine.rb:658:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.5.2/lib/rails/engine.rb:658:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.5.2/lib/rails/application.rb:452:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.5.2/lib/rails/engine.rb:453:in `load_tasks'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `method_missing'
/usr/share/redmine-3.2.1/Rakefile:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jkraemer** [comment]
What other plugins do you have installed? Chances are one of them fails to properly namespace it's code and defines a ::QueriesHelperPatch module in the top level namespace. This blocks autoloading of this plugin's queries_helper_patch file, leading to the error you see.
